
# Site settings
title: Kyle Hall's Blog
email: hallkd47@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog to write about Scala, Javascript, and being a developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kylehallblog.com" # the base hostname & protocol for your site
twitter_username: kylohall
github_username:  kyle-hall

# Build settings
markdown: kramdown
