
# Site settings
title: Kyle Hall's Blog
email: hallkd47@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog, I'll be talking about programming, particularly in Scala,
  and what it's like to be a developer who really doesn't feel they
  should get to be called one.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kylehallblog.com" # the base hostname & protocol for your site
twitter_username: kylohall
github_username:  kyle-hall

# Build settings
markdown: kramdown
